adj1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
adj2 = input("Enter a second adjective: ")
verb1 = input("Enter a verb with ing: ")
adj3 = input("Enter a third adjective: ")

print(f"today i went to a {adj1} zoo")
print(f"in an exhibit, I saw a {noun1}")
print(f"{noun1} was {adj2} and {verb1}")
print(f"I was {adj3}!")